using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityToolbag;

public class TileGenerator : MonoBehaviour {

    public static TileGenerator Instance { get { return GetInstance(); } }
    public List<TileGeneratorNode> TileGeneratorNodes { get { return tileGeneratorNodes; } }

    public Vector2 TileSize { get { return GetTileSize(); } }

    private static TileGenerator instance;

    [SerializeField] [Reorderable] private List<TileGeneratorNode> tileGeneratorNodes = new List<TileGeneratorNode>();

    public void GenerateTile(Vector2 gridPosition) {
        TileGeneratorNode matchingTileGeneratorNode = null;

        for (int i = tileGeneratorNodes.Count - 1; i >= 0; i--) {
            TileGeneratorNode tileGeneratorNode = tileGeneratorNodes[i];
            TileCondition falseCondition = tileGeneratorNode.TileConditions.Find(x => !x.Check(gridPosition));

            if (falseCondition == null) {
                matchingTileGeneratorNode = tileGeneratorNode;
                break;
            } 
        }

        Tile tile = GetTile(matchingTileGeneratorNode.Prefab, matchingTileGeneratorNode.TileType, gridPosition);
        if (tile.TileType == TileType.Empty) {
            if(LevelEditorTileGrid.Instance.Contains(gridPosition)) {
                LevelEditorTileGrid.Instance.RemoveTile(gridPosition);
            }
        } else {
            LevelEditorTileGrid.Instance.SetTile(gridPosition, tile);

            foreach (TileAction tileAction in matchingTileGeneratorNode.TileActions) {
                tileAction.Do(gridPosition);
            }
        }
    }

    public void GenerateTiles(List<Vector2> gridPositions) {
        foreach (Vector2 gridPosition in gridPositions) {
            GenerateTile(gridPosition);
        }
    }

    public void RegenerateAutoGeneratedTiles() {
        List<TileGeneratorNode> autoGenerateTileGeneratorNodes = tileGeneratorNodes.FindAll(x => !x.UserGenerated);
        List<TileType> autoGeneratedTileTypes = new List<TileType>();
        autoGenerateTileGeneratorNodes.ForEach(x => autoGeneratedTileTypes.Add(x.TileType));

        foreach (TileType tileType in autoGeneratedTileTypes) {
            List<Vector2> tileTypeGridPositions = LevelEditorTileGrid.Instance.GetGridPositionsByTileType(tileType);

            tileTypeGridPositions.ForEach(x => LevelEditorTileGrid.Instance.RemoveTile(x));
            tileTypeGridPositions.ForEach(x => {
                GenerateTile(x);
            });
        }
    }

    private bool CheckTileTypeUserGenerated(TileType tileType) {
        TileGeneratorNode tileGeneratorNode = tileGeneratorNodes.Find(x =>  x.TileType == tileType);
        return tileGeneratorNode.UserGenerated;
    }

    private Tile GetTile(GameObject prefab, TileType tileType, Vector2 gridPosition) {
        if(tileType == TileType.Empty) { return new Tile() { TileType = TileType.Empty }; }

        float nodeSize = LevelEditorGridNodeSize.Instance.Size;
        Vector2 tilePosition = GridHelper.GridToNodePosition(gridPosition, nodeSize);

        GameObject tileGameObject = ObjectPool.Instance.GetObjectForType(prefab.name, false);
        tileGameObject.transform.position = tilePosition;
        bool userGenerated = CheckTileTypeUserGenerated(tileType);
        string tileName = "";

        if(!userGenerated) {
            tileName += "AutoGenerated ";
        }

        tileName += tileType.ToString() + " " + gridPosition.ToString();
        tileGameObject.name = tileName;

        Tile tile = new Tile() {
            TileType = tileType,
            GameObject = tileGameObject,
            UserGenerated = userGenerated,
        };

        return tile;
    }

    private void SetTilesBasedOnTileValue() {
        Array enumArray = Enum.GetValues(typeof(TileType));
        int enumCount = enumArray.Length;

        if (tileGeneratorNodes.Count == enumCount) { return; }

        int index = 0;
        IEnumerable<TileType> TileTypeIEnumerable = enumArray.Cast<TileType>();

        foreach (TileType tileType in TileTypeIEnumerable) {
            if (tileGeneratorNodes.Count <= index) {
                tileGeneratorNodes.Insert(index, new TileGeneratorNode() {
                    TileType = tileType,
                });
            } else {
                tileGeneratorNodes[index].TileType = tileType;
            }
            index++;
        }
    }

    private static TileGenerator GetInstance() {
        if (instance == null) {
            instance = GameObject.FindObjectOfType<TileGenerator>();
        }
        return instance;
    }

    private void Reset() {
        SetTilesBasedOnTileValue();
    }

    private void OnValidate() {
        SetTilesBasedOnTileValue();
    }

    private Vector2 GetTileSize() {
        float tileWidth = tileGeneratorNodes.Find(x => x.TileType == TileType.Standard).Prefab.transform.localScale.x;
        float tileHeight = tileWidth;
        Vector2 tileSize = new Vector2(tileWidth, tileHeight);
        return tileSize;
    }

}
