using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityToolbag;

public class TileGenerator : MonoBehaviour {

    public static TileGenerator Instance { get { return GetInstance(); } }
    public List<TileGeneratorNode> TileGeneratorNodes { get { return tileGeneratorNodes; } }

    private static TileGenerator instance;

    [SerializeField] [Reorderable] private List<TileGeneratorNode> tileGeneratorNodes = new List<TileGeneratorNode>();
    [SerializeField] private bool debugMode = false;

    public void GenerateTile(Vector2 gridPosition) {
        TileGeneratorNode matchingTileGeneratorNode = null;

        if(debugMode) {
            Debug.Log("_____");
            Debug.Log("gridPos : " + gridPosition);
        }
        for (int i = tileGeneratorNodes.Count - 1; i >= 0; i--) {
            TileGeneratorNode tileGeneratorNode = tileGeneratorNodes[i];
            TileCondition falseCondition = tileGeneratorNode.TileConditions.Find(x => !x.Check(gridPosition));

            if (falseCondition == null) {
                matchingTileGeneratorNode = tileGeneratorNode;
                break;
            } else if (debugMode) {
                Debug.Log("false condition for " + tileGeneratorNode.TileType.ToString() + " : " + falseCondition.name);
            }
        }
        if (debugMode) {
            Debug.Log("TileType : " + matchingTileGeneratorNode.TileType);
        }

        Tile tile = GetTile(matchingTileGeneratorNode.Prefab, matchingTileGeneratorNode.TileType, gridPosition, Vector2.zero);
        if (tile.TileType == TileType.Empty) { return; }

        TileGrid.SetTile(gridPosition, tile);

        foreach(TileAction tileAction in matchingTileGeneratorNode.TileActions) {
            tileAction.Do(gridPosition);
        }
    }

    public void GenerateTiles(List<Vector2> gridPositions) {
        foreach (Vector2 gridPosition in gridPositions) {
            GenerateTile(gridPosition);
        }
    }

    public void RegenerateAutoGeneratedTiles() {
        List<TileGeneratorNode> autoGenerateTileGeneratorNodes = tileGeneratorNodes.FindAll(x => !x.UserGenerated);
        List<TileType> autoGeneratedTileTypes = new List<TileType>();
        autoGenerateTileGeneratorNodes.ForEach(x => autoGeneratedTileTypes.Add(x.TileType));

        foreach (TileType tileType in autoGeneratedTileTypes) {
            List<Vector2> tileTypeGridPositions = TileGrid.GetGridPositionsByTileType(tileType);

            tileTypeGridPositions.ForEach(x => TileGrid.RemoveTile(x));
            tileTypeGridPositions.ForEach(x => {
                GenerateTile(x);
            });
        }
    }

    private bool CheckTileTypeUserGenerated(TileType tileType) {
        TileGeneratorNode tileGeneratorNode = tileGeneratorNodes.Find(x =>  x.TileType == tileType);
        return tileGeneratorNode.UserGenerated;
    }

    private Tile GetTile(GameObject prefab, TileType tileType, Vector2 gridPosition, Vector2 direction) {
        if(tileType == TileType.Empty) { return new Tile() { TileType = TileType.Empty }; }

        Vector2 tilePosition = TileGrid.GridToTilePosition(gridPosition);

        GameObject tileGameObject = Instantiate(prefab, tilePosition, new Quaternion());
        bool userGenerated = CheckTileTypeUserGenerated(tileType);
        string tileName = "";

        if(!userGenerated) {
            tileName += "AutoGenerated ";
        }

        tileName += tileType.ToString() + " " + gridPosition.ToString();
        tileGameObject.name = tileName;

        Tile tile = new Tile() {
            TileType = tileType,
            GameObject = tileGameObject,
            UserGenerated = userGenerated,
        };

        return tile;
    }

    private void SetTilesBasedOnTileValue() {
        Array enumArray = Enum.GetValues(typeof(TileType));
        int enumCount = enumArray.Length;

        if (tileGeneratorNodes.Count == enumCount) { return; }

        int index = 0;
        IEnumerable<TileType> TileTypeIEnumerable = enumArray.Cast<TileType>();

        foreach (TileType tileType in TileTypeIEnumerable) {
            if (tileGeneratorNodes.Count <= index) {
                tileGeneratorNodes.Insert(index, new TileGeneratorNode() {
                    TileType = tileType,
                });
            } else {
                tileGeneratorNodes[index].TileType = tileType;
            }
            index++;
        }
    }

    private static TileGenerator GetInstance() {
        if (instance == null) {
            instance = GameObject.FindObjectOfType<TileGenerator>();
        }
        return instance;
    }

    private void Reset() {
        SetTilesBasedOnTileValue();
    }

    private void OnValidate() {
        SetTilesBasedOnTileValue();
    }


    private void Awake() {
        float tileWidth = tileGeneratorNodes.Find(x => x.TileType == TileType.Standard).Prefab.transform.localScale.x;
        TileGrid.SetTileSize(tileWidth);
    }

}
